- update to the new 10.27 release - update .security2, .security patch - regenerate man pages - remove jbig, hpcd

diff --git a/netpbm-10.22-security2.patch b/netpbm-10.22-security2.patch
--- a/netpbm-10.22-security2.patch
+++ b/netpbm-10.22-security2.patch
@@ -1,109 +1,53 @@
---- netpbm-10.22/editor/ppmquantall.security2	2003-12-31 04:56:24.000000000 +0100
-+++ netpbm-10.22/editor/ppmquantall	2004-06-30 14:55:13.820546555 +0200
-@@ -63,13 +63,8 @@
-     heights=(${heights[*]} `grep -v '^#' $i | sed '1d; s/.* //; 2q'`)
- done
+--- netpbm-10.27/converter/other/anytopnm.security2	2004-10-13 17:05:53.000000000 +0200
++++ netpbm-10.27/converter/other/anytopnm	2005-03-29 14:03:43.449904176 +0200
+@@ -522,11 +522,7 @@ else
+     inputFile="-"
+ fi
  
--tempdir="${TMPDIR-/tmp}/ppmquantall.$$"
+-tempdir="${TMPDIR-/tmp}/anytopnm.$$"
 -mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
 -chmod 700 $tempdir
 -
 -trap 'rm -rf $tempdir' 0 1 3 15
--
--all=$tempdir/pqa.all.$$
-+all=$(mktemp -t pqa.all.XXXXXXXXXX) || exit 1
-+rm -f $all
++tempdir=$(mktemp -d -t anytopnm.XXXXXXXXXX) || exit 1
  
- pnmcat -topbottom -jleft -white ${files[@]} | ppmquant $newcolors > $all
- if [ $? != 0 ]; then
---- netpbm-10.22/editor/pnmmargin.security2	2003-12-31 05:01:26.000000000 +0100
-+++ netpbm-10.22/editor/pnmmargin	2004-06-30 15:00:53.814556218 +0200
-@@ -11,16 +11,11 @@
- # documentation.  This software is provided "as is" without express or
- # implied warranty.
+ findAwk;
  
--tempdir="${TMPDIR-/tmp}/pnmmargin.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--
--trap 'rm -rf $tempdir' 0 1 3 15
--
--tmp1=$tempdir/pnmm1
--tmp2=$tempdir/pnmm2
--tmp3=$tempdir/pnmm3
--tmp4=$tempdir/pnmm4
-+tmpdir=$(mktemp -d -t ppmmargin.XXXXXXX) || exit 1
-+tmp1="$tmpdir/tmp1"
-+tmp2="$tmpdir/tmp2"
-+tmp3="$tmpdir/tmp3"
-+tmp4="$tmpdir/tmp4"
- 
- color="-gofigure"
- 
-@@ -39,6 +34,9 @@
- 	shift
- 	if [ ! ${1-""} ] ; then
- 	    echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
-+            if [ -d "$tmpdir" ]; then
-+                rm -rf "$tmpdir"
-+            fi
- 	    exit 1
- 	fi
- 	color="$1"
-@@ -46,6 +44,9 @@
- 	;;
- 	-* )
- 	echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
-+        if [ -d "$tmpdir" ]; then
-+            rm -rf "$tmpdir"
-+        fi
- 	exit 1
- 	;;
- 	* )
-@@ -56,6 +57,9 @@
- 
- if [ ! ${1-""} ] ; then
-     echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
-+    if [ -d "$tmpdir" ]; then
-+        rm -rf "$tmpdir"
+@@ -549,9 +545,17 @@ if [ "$filetype" = "unknown" ]; then
+     echo "$progname: unknown file type.  " \
+         "'file' says mime type is '$mimeType', " 1>&2
+     echo "type description is '$typeDescription'" 1>&2
++    if [ -d "$tempdir" ] ; then
++        rm -rf "$tempdir"
 +    fi
-     exit 1
- fi
- size="$1"
-@@ -63,6 +67,9 @@
- 
- if [ ${2-""} ] ; then
-     echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
-+    if [ -d "$tmpdir" ]; then
-+        rm -rf "$tmpdir"
-+    fi
-     exit 1
- fi
- 
-@@ -86,3 +93,7 @@
- # Cat things together.
- pnmcat -lr $tmp2 $tmp1 $tmp2 > $tmp4
- pnmcat -tb $tmp3 $tmp4 $tmp3
 +
-+if [ -d "$tmpdir" ]; then
-+    rm -rf "$tmpdir"
+     exit 1
+     fi
+ 
+ convertIt $file $filetype
+ 
++if [ -d "$tempdir" ] ; then
++    rm -rf "$tempdir"
 +fi
---- netpbm-10.22/editor/pamstretch-gen.security2	2003-12-31 04:47:10.000000000 +0100
-+++ netpbm-10.22/editor/pamstretch-gen	2004-06-30 16:02:24.705968769 +0200
-@@ -31,10 +31,7 @@
-   exit 1
- fi
++
+ exit 0
+--- netpbm-10.27/converter/ppm/ppmtompeg/parallel.c.security2	2005-03-05 06:07:50.000000000 +0100
++++ netpbm-10.27/converter/ppm/ppmtompeg/parallel.c	2005-03-29 14:03:43.452903720 +0200
+@@ -1058,8 +1058,11 @@ GetRemoteFrame(MpegFrame * const frameP,
+             int numBytes;  /* Number of data bytes in message */
+             FILE * filePtr;
+             char fileName[256];
++#define TMPFILE_TEMPLATE "/tmp/ppmtompeg.XXXXXX"
  
--tempdir="${TMPDIR-/tmp}/pamstretch-gen.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--tempfile=$tempdir/pnmig
-+tempfile=$(mktemp /tmp/pnmig.XXXXXXXXXX) || exit 1
+-            sprintf(fileName, "/tmp/foobar%d", machineNumber);
++            strcpy(fileName, TMPFILE_TEMPLATE);
++            if (-1 == mkstemp(fileName))
++                pm_error( "could not create temporary convolution file");
+             filePtr = fopen(fileName, "wb");
  
- trap 'rm -rf $tempdir' 0 1 3 15
- 
---- netpbm-10.22/editor/ppmfade.security2	2003-08-18 01:41:59.000000000 +0200
-+++ netpbm-10.22/editor/ppmfade	2004-06-30 14:51:08.412822427 +0200
+             /* read in stuff, write to file, perform local conversion */
+--- netpbm-10.27/editor/ppmfade.security2	2005-03-16 22:10:39.000000000 +0100
++++ netpbm-10.27/editor/ppmfade	2005-03-29 14:29:07.975141112 +0200
 @@ -14,6 +14,7 @@
  #
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
@@ -112,7 +56,7 @@
  
  my $SPREAD =  1;
  my $SHIFT =   2;
-@@ -116,20 +117,26 @@
+@@ -116,20 +117,26 @@ if ($first_file ne "undefined") {
  
  print("Frames are " . $width . "W x " . $height . "H\n");
  
@@ -143,7 +87,30 @@
  }
  
  #
-@@ -152,148 +159,150 @@
+@@ -137,14 +144,14 @@ if ($last_file eq "undefined") {
+ #
+ 
+ # Here's what our temporary files are:
+-#   junk1$$.ppm: The original (fade-from) image
+-#   junk2$$.ppm: The target (fade-from) image
+-#   junk3$$.ppm: The frame of the fade for the current iteration of the 
+-#                the for loop.
+-#   junk1a$$.ppm: If the fade involves a ppmmix sequence from one intermediate
+-#                 image to another, this is the first frame of that 
+-#                 sequence.
+-#   junk2a$$.ppm: This is the last frame of the above-mentioned ppmmix sequence
++#   $tmpdir/junk1$$.ppm: The original (fade-from) image
++#   $tmpdir/junk2$$.ppm: The target (fade-from) image
++#   $tmpdir/junk3$$.ppm: The frame of the fade for the current iteration of the 
++#                	 the for loop.
++#   $tmpdir/junk1a$$.ppm: If the fade involves a ppmmix sequence from one intermediate
++#                         image to another, this is the first frame of that 
++#                         sequence.
++#   $tmpdir/junk2a$$.ppm: This is the last frame of the above-mentioned ppmmix sequence
+ 
+ my $i;    # Frame number
+ for ($i = 1; $i <= $nframes; $i++) {
+@@ -152,148 +159,148 @@ for ($i = 1; $i <= $nframes; $i++) {
      if ($mode eq $SPREAD) {
          if ($i <= 10) {
              my $n = $spline20[$i] * 100;
@@ -295,34 +262,34 @@
 -            system("rgb3toppm junko$$.ppm junko$$.ppm junko$$.ppm " .
 -                   ">junk2o$$.ppm");
 +            system("ppmtopgm $tmpdir/junk2$$.ppm | pgmbentley >$tmpdir/junko$$.ppm");
-+            system("rgb3toppm $tmpdir/junko$$.ppm j$tmpdir/unko$$.ppm $tmpdir/junko$$.ppm " .
++            system("rgb3toppm $tmpdir/junko$$.ppm $tmpdir/junko$$.ppm $tmpdir/junko$$.ppm " .
 +                   ">$tmpdir/junk2o$$.ppm");
          }
      } elsif ($mode eq $BLOCK) {
          if ($i <= 10) {
              my $n = 1 - 1.9*$spline20[$i];
--            system("pnmscale $n junk1$$.ppm | " .
--                   "pnmscale -width $width -height $height >junk3$$.ppm");
-+            system("pnmscale $n $tmpdir/junk1$$.ppm | " .
-+                   "pnmscale -width $width -height $height >$tmpdir/junk3$$.ppm");
+-            system("pamscale $n junk1$$.ppm | " .
+-                   "pamscale -width $width -height $height >junk3$$.ppm");
++            system("pamscale $n $tmpdir/junk1$$.ppm | " .
++                   "pamscale -width $width -height $height >$tmpdir/junk3$$.ppm");
          } elsif ($i <= 20) {
              my $n = $spline10[$i-10];
 -            system("ppmmix $n junk1a$$.ppm junk2a$$.ppm >junk3$$.ppm");
 +            system("ppmmix $n $tmpdir/junk1a$$.ppm $tmpdir/junk2a$$.ppm >$tmpdir/junk3$$.ppm");
          } else {
              my $n = 1 - 1.9*$spline20[31-$i];
--            system("pnmscale $n junk2$$.ppm | " .
--                   "pnmscale -width $width -height $height >junk3$$.ppm");
-+            system("pnmscale $n $tmpdir/junk2$$.ppm | " .
-+                   "pnmscale -width $width -height $height >$tmpdir/junk3$$.ppm");
+-            system("pamscale $n junk2$$.ppm | " .
+-                   "pamscale -width $width -height $height >junk3$$.ppm");
++            system("pamscale $n $tmpdir/junk2$$.ppm | " .
++                   "pamscale -width $width -height $height >$tmpdir/junk3$$.ppm");
          }
          if ($i == 10) {
 -            system("cp", "junk3$$.ppm", "junk1a$$.ppm");
--            system("pnmscale $n junk2$$.ppm | " .
--                   "pnmscale -width $width -height $height >junk2a$$.ppm");
+-            system("pamscale $n junk2$$.ppm | " .
+-                   "pamscale -width $width -height $height >junk2a$$.ppm");
 +            system("cp", "$tmpdir/junk3$$.ppm", "$tmpdir/junk1a$$.ppm");
-+            system("pnmscale $n $tmpdir/junk2$$.ppm | " .
-+                   "pnmscale -width $width -height $height >$tmpdir/junk2a$$.ppm");
++            system("pamscale $n $tmpdir/junk2$$.ppm | " .
++                   "pamscale -width $width -height $height >$tmpdir/junk2a$$.ppm");
          }    
      } elsif ($mode eq $MIX) {
          my $fade_factor = sqrt(1/($nframes-$i+1));
@@ -341,15 +308,117 @@
  #  Clean up shop.
  #
 -system("rm junk*$$.ppm");
-+#system("rm junk*$$.ppm");
-+# As the temporary files are automatically deleted, nothing is needed for
-+# cleanup any more.
++system("rm $tmpdir/junk*$$.ppm");
  
  exit(0);
  
---- netpbm-10.22/editor/ppmshadow.security2	2004-01-31 04:35:48.000000000 +0100
-+++ netpbm-10.22/editor/ppmshadow	2004-06-30 16:01:24.378413183 +0200
-@@ -27,9 +27,10 @@
+--- netpbm-10.27/editor/ppmquantall.security2	2005-03-17 00:44:03.000000000 +0100
++++ netpbm-10.27/editor/ppmquantall	2005-03-29 14:03:43.441905392 +0200
+@@ -63,13 +63,8 @@ for i in ${files[@]}; do
+     heights=(${heights[*]} `grep -v '^#' $i | sed '1d; s/.* //; 2q'`)
+ done
+ 
+-tempdir="${TMPDIR-/tmp}/ppmquantall.$$"
+-mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
+-chmod 700 $tempdir
+-
+-trap 'rm -rf $tempdir' 0 1 3 15
+-
+-all=$tempdir/pqa.all.$$
++all=$(mktemp -t pqa.all.XXXXXXXXXX) || exit 1
++rm -f $all
+ 
+ pnmcat -topbottom -jleft -white ${files[@]} | pnmquant $newcolors > $all
+ if [ $? != 0 ]; then
+--- netpbm-10.27/editor/pnmmargin.security2	2003-12-31 05:01:26.000000000 +0100
++++ netpbm-10.27/editor/pnmmargin	2005-03-29 14:03:43.442905240 +0200
+@@ -11,16 +11,11 @@
+ # documentation.  This software is provided "as is" without express or
+ # implied warranty.
+ 
+-tempdir="${TMPDIR-/tmp}/pnmmargin.$$"
+-mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
+-chmod 700 $tempdir
+-
+-trap 'rm -rf $tempdir' 0 1 3 15
+-
+-tmp1=$tempdir/pnmm1
+-tmp2=$tempdir/pnmm2
+-tmp3=$tempdir/pnmm3
+-tmp4=$tempdir/pnmm4
++tmpdir=$(mktemp -d -t ppmmargin.XXXXXXX) || exit 1
++tmp1="$tmpdir/tmp1"
++tmp2="$tmpdir/tmp2"
++tmp3="$tmpdir/tmp3"
++tmp4="$tmpdir/tmp4"
+ 
+ color="-gofigure"
+ 
+@@ -39,6 +34,9 @@ while true ; do
+ 	shift
+ 	if [ ! ${1-""} ] ; then
+ 	    echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
++            if [ -d "$tmpdir" ]; then
++                rm -rf "$tmpdir"
++            fi
+ 	    exit 1
+ 	fi
+ 	color="$1"
+@@ -46,6 +44,9 @@ while true ; do
+ 	;;
+ 	-* )
+ 	echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
++        if [ -d "$tmpdir" ]; then
++            rm -rf "$tmpdir"
++        fi
+ 	exit 1
+ 	;;
+ 	* )
+@@ -56,6 +57,9 @@ done
+ 
+ if [ ! ${1-""} ] ; then
+     echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
++    if [ -d "$tmpdir" ]; then
++        rm -rf "$tmpdir"
++    fi
+     exit 1
+ fi
+ size="$1"
+@@ -63,6 +67,9 @@ shift
+ 
+ if [ ${2-""} ] ; then
+     echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
++    if [ -d "$tmpdir" ]; then
++        rm -rf "$tmpdir"
++    fi
+     exit 1
+ fi
+ 
+@@ -86,3 +93,7 @@ pamflip -rotate90 $tmp2 > $tmp3
+ # Cat things together.
+ pnmcat -lr $tmp2 $tmp1 $tmp2 > $tmp4
+ pnmcat -tb $tmp3 $tmp4 $tmp3
++
++if [ -d "$tmpdir" ]; then
++    rm -rf "$tmpdir"
++fi
+--- netpbm-10.27/editor/pamstretch-gen.security2	2004-07-25 02:01:24.000000000 +0200
++++ netpbm-10.27/editor/pamstretch-gen	2005-03-29 14:03:43.443905088 +0200
+@@ -31,10 +31,7 @@ if [ "$1" = "" ]; then
+   exit 1
+ fi
+ 
+-tempdir="${TMPDIR-/tmp}/pamstretch-gen.$$"
+-mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
+-chmod 700 $tempdir
+-tempfile=$tempdir/pnmig
++tempfile=$(mktemp /tmp/pnmig.XXXXXXXXXX) || exit 1
+ 
+ trap 'rm -rf $tempdir' 0 1 3 15
+ 
+--- netpbm-10.27/editor/ppmshadow.security2	2005-03-16 22:10:25.000000000 +0100
++++ netpbm-10.27/editor/ppmshadow	2005-03-29 14:03:43.447904480 +0200
+@@ -27,9 +27,10 @@ use strict;
  my $true=1; my $false=0;
  
  my $tmpdir = $ENV{TMPDIR} || "/tmp";
@@ -363,51 +432,3 @@
  
  #   Process command line options
  
---- netpbm-10.22/converter/other/anytopnm.security2	2003-12-31 04:49:34.000000000 +0100
-+++ netpbm-10.22/converter/other/anytopnm	2004-06-30 14:58:25.242904602 +0200
-@@ -503,11 +503,7 @@
-     inputFile="-"
- fi
- 
--tempdir="${TMPDIR-/tmp}/anytopnm.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--
--trap 'rm -rf $tempdir' 0 1 3 15
-+tempdir=$(mktemp -d -t anytopnm.XXXXXXXXXX) || exit 1
- 
- # Take out all spaces
- # Find the filename extension for last-ditch efforts later
-@@ -528,9 +524,17 @@
-     echo "$progname: unknown file type.  " \
-         "'file' says mime type is '$mimeType', " 1>&2
-     echo "type description is '$typeDescription'" 1>&2
-+    if [ -d "$tempdir" ] ; then
-+        rm -rf "$tempdir"
-+    fi
-+
-     exit 1
-     fi
- 
- convertIt $file $filetype
- 
-+if [ -d "$tempdir" ] ; then
-+    rm -rf "$tempdir"
-+fi
-+
- exit 0
---- netpbm-10.22/converter/ppm/ppmtompeg/parallel.c.security2	2004-06-30 14:51:08.365828224 +0200
-+++ netpbm-10.22/converter/ppm/ppmtompeg/parallel.c	2004-06-30 14:51:08.409822797 +0200
-@@ -609,8 +609,11 @@
-             int numBytes;  /* Number of data bytes in message */
-             FILE * filePtr;
-             char fileName[256];
-+#define TMPFILE_TEMPLATE "/tmp/ppmtompeg.XXXXXX"
- 
--            sprintf(fileName, "/tmp/foobar%d", machineNumber);
-+            strcpy(fileName, TMPFILE_TEMPLATE);
-+            if (-1 == mkstemp(fileName))
-+                pm_error( "could not create temporary convolution file");
-             filePtr = fopen(fileName, "wb");
- 
-             /* read in stuff, SafeWrite to file, perform local conversion */
