- update to 10.47.04 (it is now stable) (#529525) - fixes #502917, #482850, #482847

diff --git a/netpbm-security-scripts.patch b/netpbm-security-scripts.patch
--- a/netpbm-security-scripts.patch
+++ b/netpbm-security-scripts.patch
@@ -1,20 +1,19 @@
-diff -up netpbm-10.35.48/converter/other/anytopnm.security2 netpbm-10.35.48/converter/other/anytopnm
---- netpbm-10.35.48/converter/other/anytopnm.security2	2008-08-03 22:07:04.000000000 +0200
-+++ netpbm-10.35.48/converter/other/anytopnm	2008-08-04 07:11:46.000000000 +0200
-@@ -506,11 +506,7 @@ else
+diff -up netpbm-10.47.04/converter/other/anytopnm.security2 netpbm-10.47.04/converter/other/anytopnm
+--- netpbm-10.47.04/converter/other/anytopnm.security2	2009-10-21 13:39:06.000000000 +0200
++++ netpbm-10.47.04/converter/other/anytopnm	2009-10-21 14:51:49.000000000 +0200
+@@ -510,10 +510,7 @@ else
      inputFile="-"
  fi
  
 -tempdir="${TMPDIR-/tmp}/anytopnm.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--
+-mkdir -m 0700 $tempdir || \
+-  { echo "Could not create temporary file. Exiting."; exit 1;}
 -trap 'rm -rf $tempdir' 0
 +tempdir=$(mktemp -d -t anytopnm.XXXXXXXXXX) || exit 1
  
  # Take out all spaces
  # Find the filename extension for last-ditch efforts later
-@@ -536,9 +532,17 @@ if [ "$filetype" = "unknown" ]; then
+@@ -539,9 +536,17 @@ if [ "$filetype" = "unknown" ]; then
      echo "$progname: unknown file type.  " \
          "'file' says mime type is '$mimeType', " 1>&2
      echo "type description is '$typeDescription'" 1>&2
@@ -32,32 +31,30 @@ diff -up netpbm-10.35.48/converter/other/anytopnm.security2 netpbm-10.35.48/conv
 +fi
 +
  exit 0
-diff -up netpbm-10.35.48/editor/pamstretch-gen.security2 netpbm-10.35.48/editor/pamstretch-gen
---- netpbm-10.35.48/editor/pamstretch-gen.security2	2008-08-03 22:06:45.000000000 +0200
-+++ netpbm-10.35.48/editor/pamstretch-gen	2008-08-04 07:11:46.000000000 +0200
-@@ -31,10 +31,7 @@ if [ "$1" = "" ]; then
+diff -up netpbm-10.47.04/editor/pamstretch-gen.security2 netpbm-10.47.04/editor/pamstretch-gen
+--- netpbm-10.47.04/editor/pamstretch-gen.security2	2009-10-21 13:38:57.000000000 +0200
++++ netpbm-10.47.04/editor/pamstretch-gen	2009-10-21 14:53:28.000000000 +0200
+@@ -31,9 +31,7 @@ if [ "$1" = "" ]; then
    exit 1
  fi
  
 -tempdir="${TMPDIR-/tmp}/pamstretch-gen.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--tempfile=$tempdir/pnmig
+-mkdir -m 0700 $tempdir || \
+-  { echo "Could not create temporary file. Exiting."; exit 1;}
 +tempfile=$(mktemp /tmp/pnmig.XXXXXXXXXX) || exit 1
- 
  trap 'rm -rf $tempdir' 0 1 3 15
  
-diff -up netpbm-10.35.48/editor/pnmmargin.security2 netpbm-10.35.48/editor/pnmmargin
---- netpbm-10.35.48/editor/pnmmargin.security2	2008-08-03 22:06:45.000000000 +0200
-+++ netpbm-10.35.48/editor/pnmmargin	2008-08-04 07:11:46.000000000 +0200
-@@ -11,16 +11,11 @@
+ tempfile=$tempdir/pnmig
+diff -up netpbm-10.47.04/editor/pnmmargin.security2 netpbm-10.47.04/editor/pnmmargin
+--- netpbm-10.47.04/editor/pnmmargin.security2	2009-10-21 13:38:57.000000000 +0200
++++ netpbm-10.47.04/editor/pnmmargin	2009-10-21 14:55:40.000000000 +0200
+@@ -11,15 +11,11 @@
  # documentation.  This software is provided "as is" without express or
  # implied warranty.
  
 -tempdir="${TMPDIR-/tmp}/pnmmargin.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--
+-mkdir -m 0700 $tempdir || \
+-  { echo "Could not create temporary file. Exiting." 1>&2; exit 1;}
 -trap 'rm -rf $tempdir' 0 1 3 15
 -
 -tmp1=$tempdir/pnmm1
@@ -71,18 +68,18 @@ diff -up netpbm-10.35.48/editor/pnmmargin.security2 netpbm-10.35.48/editor/pnmma
 +tmp4="$tmpdir/tmp4"
  
  color="-gofigure"
- 
-@@ -39,6 +34,9 @@ while true ; do
+ plainopt=""
+@@ -43,6 +39,9 @@ while true ; do
  	shift
  	if [ ! ${1-""} ] ; then
- 	    echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
+        	    echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
 +            if [ -d "$tmpdir" ]; then
 +                rm -rf "$tmpdir"
 +            fi
  	    exit 1
  	fi
  	color="$1"
-@@ -46,6 +44,9 @@ while true ; do
+@@ -50,6 +49,9 @@ while true ; do
  	;;
  	-* )
  	echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
@@ -92,7 +89,7 @@ diff -up netpbm-10.35.48/editor/pnmmargin.security2 netpbm-10.35.48/editor/pnmma
  	exit 1
  	;;
  	* )
-@@ -56,6 +57,9 @@ done
+@@ -60,6 +62,9 @@ done
  
  if [ ! ${1-""} ] ; then
      echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
@@ -102,7 +99,7 @@ diff -up netpbm-10.35.48/editor/pnmmargin.security2 netpbm-10.35.48/editor/pnmma
      exit 1
  fi
  size="$1"
-@@ -63,6 +67,9 @@ shift
+@@ -67,6 +72,9 @@ shift
  
  if [ ${2-""} ] ; then
      echo "usage: $0 [-white|-black|-color <colorspec>] <size> [pnmfile]" 1>&2
@@ -112,17 +109,19 @@ diff -up netpbm-10.35.48/editor/pnmmargin.security2 netpbm-10.35.48/editor/pnmma
      exit 1
  fi
  
-@@ -86,3 +93,7 @@ pamflip -rotate90 $tmp2 > $tmp3
- # Cat things together.
- pnmcat -lr $tmp2 $tmp1 $tmp2 > $tmp4
- pnmcat -tb $tmp3 $tmp4 $tmp3
-+
+@@ -103,6 +111,6 @@ else
+     pnmcat -tb $plainopt $tmp3 $tmp4 $tmp3
+ fi
+ 
+-
+-
+-
 +if [ -d "$tmpdir" ]; then
 +    rm -rf "$tmpdir"
 +fi
-diff -up netpbm-10.35.48/editor/ppmfade.security2 netpbm-10.35.48/editor/ppmfade
---- netpbm-10.35.48/editor/ppmfade.security2	2008-08-03 22:06:45.000000000 +0200
-+++ netpbm-10.35.48/editor/ppmfade	2008-08-04 07:11:46.000000000 +0200
+diff -up netpbm-10.47.04/editor/ppmfade.security2 netpbm-10.47.04/editor/ppmfade
+--- netpbm-10.47.04/editor/ppmfade.security2	2009-10-21 13:38:57.000000000 +0200
++++ netpbm-10.47.04/editor/ppmfade	2009-10-21 15:03:01.000000000 +0200
 @@ -14,6 +14,7 @@
  #
  #-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-
@@ -131,7 +130,7 @@ diff -up netpbm-10.35.48/editor/ppmfade.security2 netpbm-10.35.48/editor/ppmfade
  
  my $SPREAD =  1;
  my $SHIFT =   2;
-@@ -116,20 +117,26 @@ if ($first_file ne "undefined") {
+@@ -111,20 +112,26 @@ if ($first_file ne "undefined") {
  
  print("Frames are " . $width . "W x " . $height . "H\n");
  
@@ -162,7 +161,7 @@ diff -up netpbm-10.35.48/editor/ppmfade.security2 netpbm-10.35.48/editor/ppmfade
  }
  
  #
-@@ -137,14 +144,14 @@ if ($last_file eq "undefined") {
+@@ -132,14 +139,14 @@ if ($last_file eq "undefined") {
  #
  
  # Here's what our temporary files are:
@@ -185,7 +184,7 @@ diff -up netpbm-10.35.48/editor/ppmfade.security2 netpbm-10.35.48/editor/ppmfade
  
  my $i;    # Frame number
  for ($i = 1; $i <= $nframes; $i++) {
-@@ -152,148 +159,148 @@ for ($i = 1; $i <= $nframes; $i++) {
+@@ -147,147 +154,147 @@ for ($i = 1; $i <= $nframes; $i++) {
      if ($mode eq $SPREAD) {
          if ($i <= 10) {
              my $n = $spline20[$i] * 100;
@@ -386,18 +385,16 @@ diff -up netpbm-10.35.48/editor/ppmfade.security2 netpbm-10.35.48/editor/ppmfade
 +system("rm $tmpdir/junk*$$.ppm");
  
  exit(0);
- 
-diff -up netpbm-10.35.48/editor/ppmquantall.security2 netpbm-10.35.48/editor/ppmquantall
---- netpbm-10.35.48/editor/ppmquantall.security2	2008-08-03 22:06:45.000000000 +0200
-+++ netpbm-10.35.48/editor/ppmquantall	2008-08-04 07:11:46.000000000 +0200
-@@ -70,13 +70,8 @@ for i in ${files[@]}; do
+diff -up netpbm-10.47.04/editor/ppmquantall.security2 netpbm-10.47.04/editor/ppmquantall
+--- netpbm-10.47.04/editor/ppmquantall.security2	2009-10-21 13:38:57.000000000 +0200
++++ netpbm-10.47.04/editor/ppmquantall	2009-10-21 14:52:38.000000000 +0200
+@@ -70,12 +70,8 @@ for i in ${files[@]}; do
      heights=(${heights[*]} `grep -v '^#' $i | sed '1d; s/.* //; 2q'`)
  done
  
 -tempdir="${TMPDIR-/tmp}/ppmquantall.$$"
--mkdir $tempdir || { echo "Could not create temporary file. Exiting."; exit 1;}
--chmod 700 $tempdir
--
+-mkdir -m 0700 $tempdir || \
+-  { echo "Could not create temporary file. Exiting."; exit 1;}
 -trap 'rm -rf $tempdir' 0 1 3 15
 -
 -all=$tempdir/pqa.all.$$
@@ -406,9 +403,9 @@ diff -up netpbm-10.35.48/editor/ppmquantall.security2 netpbm-10.35.48/editor/ppm
  
  pnmcat -topbottom -jleft -white ${files[@]} | pnmquant $newcolors > $all
  if [ $? != 0 ]; then
-diff -up netpbm-10.35.48/editor/ppmshadow.security2 netpbm-10.35.48/editor/ppmshadow
---- netpbm-10.35.48/editor/ppmshadow.security2	2008-08-03 22:06:45.000000000 +0200
-+++ netpbm-10.35.48/editor/ppmshadow	2008-08-04 07:11:46.000000000 +0200
+diff -up netpbm-10.47.04/editor/ppmshadow.security2 netpbm-10.47.04/editor/ppmshadow
+--- netpbm-10.47.04/editor/ppmshadow.security2	2009-10-21 13:38:57.000000000 +0200
++++ netpbm-10.47.04/editor/ppmshadow	2009-10-21 14:51:02.000000000 +0200
 @@ -72,9 +72,10 @@ sub makeConvolutionKernel($$) {
  
  
